flowchart TB
    subgraph " "
    v0["channel.empty"]
    v2["channel.fromList"]
    v7["channel.empty"]
    v8["channel.empty"]
    v17["discard_trimmed_pass"]
    v18["save_trimmed_fail"]
    v19["save_merged"]
    v30[" "]
    v34["channel.empty"]
    v37["hisat2_memory_input"]
    v40["save_unaligned"]
    v45[" "]
    v46["index_format"]
    v54[" "]
    v62["mode"]
    v63["annotation_gtf"]
    v74[" "]
    v84["channel.of"]
    v89[" "]
    v92[" "]
    end
    subgraph " "
    v1["versions"]
    v11[" "]
    v14[" "]
    v15[" "]
    v21[" "]
    v22[" "]
    v23[" "]
    v24[" "]
    v25[" "]
    v32[" "]
    v33[" "]
    v35[" "]
    v39[" "]
    v42[" "]
    v43[" "]
    v44[" "]
    v48[" "]
    v49["bai"]
    v50[" "]
    v51[" "]
    v56[" "]
    v57[" "]
    v58["bai"]
    v65[" "]
    v66[" "]
    v67[" "]
    v68[" "]
    v72[" "]
    v73["tpm"]
    v99[" "]
    v100[" "]
    v101[" "]
    v104["multiqc_report"]
    end
    subgraph "SAVETHEWHAIES_CWBDPROJECT [SAVETHEWHAIES_CWBDPROJECT]"
    subgraph "SAVETHEWHAIES_CWBDPROJECT:CWBDPROJECT [CWBDPROJECT]"
    subgraph "SAVETHEWHAIES_CWBDPROJECT:CWBDPROJECT:QC_TRIM [QC_TRIM]"
    v10(["CAT_FASTQ"])
    v13(["FASTQC"])
    v20(["FASTP"])
    v9(( ))
    v26(( ))
    end
    subgraph "SAVETHEWHAIES_CWBDPROJECT:CWBDPROJECT:ALIGN [ALIGN]"
    v31(["HISAT2_EXTRACTSPLICESITES"])
    v38(["HISAT2_BUILD"])
    v41(["HISAT2_ALIGN"])
    v47(["SAMTOOLS_SORT"])
    v36(( ))
    v52(( ))
    end
    subgraph "SAVETHEWHAIES_CWBDPROJECT:CWBDPROJECT:MARKDUP [MARKDUP]"
    v55(["PICARD_MARKDUPLICATES"])
    v59(( ))
    end
    subgraph "SAVETHEWHAIES_CWBDPROJECT:CWBDPROJECT:QUANTIFY [QUANTIFY]"
    v64(["STRINGTIE_STRINGTIE"])
    v71(["MERGE_TPM"])
    v61(( ))
    v69(( ))
    end
    v98(["MULTIQC"])
    v29(( ))
    v102(( ))
    end
    end
    subgraph "PIPELINE_INITIALISATION [PIPELINE_INITIALISATION]"
    v3(( ))
    end
    v0 --> v1
    v2 --> v3
    v7 --> v29
    v8 --> v29
    v9 --> v10
    v10 --> v11
    v10 --> v9
    v9 --> v13
    v13 --> v15
    v13 --> v14
    v13 --> v26
    v17 --> v20
    v18 --> v20
    v19 --> v20
    v9 --> v20
    v20 --> v41
    v20 --> v25
    v20 --> v24
    v20 --> v23
    v20 --> v22
    v20 --> v21
    v20 --> v26
    v30 --> v31
    v31 --> v33
    v31 --> v32
    v31 --> v41
    v31 --> v36
    v34 --> v35
    v37 --> v38
    v36 --> v38
    v38 --> v41
    v38 --> v39
    v40 --> v41
    v41 --> v47
    v41 --> v44
    v41 --> v43
    v41 --> v42
    v41 --> v52
    v45 --> v47
    v46 --> v47
    v47 --> v55
    v47 --> v51
    v47 --> v50
    v47 --> v49
    v47 --> v48
    v54 --> v55
    v55 --> v58
    v55 --> v57
    v55 --> v56
    v55 --> v59
    v55 --> v61
    v62 --> v64
    v63 --> v64
    v61 --> v64
    v64 --> v68
    v64 --> v67
    v64 --> v66
    v64 --> v65
    v64 --> v69
    v69 --> v71
    v71 --> v73
    v71 --> v72
    v74 --> v29
    v84 --> v29
    v89 --> v29
    v92 --> v29
    v29 --> v98
    v98 --> v101
    v98 --> v100
    v98 --> v99
    v98 --> v102
    v102 --> v104
    v3 --> v9
    v26 --> v29
    v52 --> v29
    v59 --> v29
